force-app/main/default/objects/Candidate_Vaccine__c/Candidate_Vaccine__c.object-meta.xml
<CustomObject>
    <label>Eligible Vaccine</label>
    <nameField>
        <displayFormat>EV{0000000}</displayFormat>
        <label>Eligibile Vaccine Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligible Vaccines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Vaccine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eligible Vaccines</relationshipLabel>
    <relationshipName>Eligible_Vaccines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Vaccine__c/fields/Eligibility_Vaccine_Group__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Vaccine_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligibility Vaccine Group</label>
    <referenceTo>Eligibility_Vaccine_Group__c</referenceTo>
    <relationshipName>Candidate_Vaccines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Vaccine__c/fields/Site_Category__c.field-meta.xml
<CustomField>
    <fullName>Site_Category__c</fullName>
    <label>Booking Visibility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Vaccine__c/fields/Vaccine_Application__c.field-meta.xml
<CustomField>
    <fullName>Vaccine_Application__c</fullName>
    <label>Vaccine Application</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Candidate_Vaccines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/Disease__c.field-meta.xml
<CustomField>
    <fullName>Disease__c</fullName>
    <label>Disease</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVID19</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Eligible</fullName>
                <default>true</default>
                <label>Not Eligible</label>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Eligibility_Vaccine_Group__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Vaccine_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eligibility Vaccine Group</label>
    <referenceTo>Eligibility_Vaccine_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Site_Category__c.field-meta.xml
<CustomField>
    <fullName>Site_Category__c</fullName>
    <label>Booking Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Site_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eligibility_Vaccine_Group__c/Eligibility_Vaccine_Group__c.object-meta.xml
<CustomObject>
    <label>Eligibility Vaccine Group</label>
    <nameField>
        <label>Eligibility Vaccine Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eligibility Vaccine Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Eligibility_Vaccine_Group__c/fields/Disease__c.field-meta.xml
<CustomField>
    <fullName>Disease__c</fullName>
    <label>Disease</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVID19</fullName>
                <default>true</default>
                <label>COVID19</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Site_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Restricted</fullName>
    </customValue>
    <masterLabel>Site Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EligibilityVaccineMassRecalcBatch.cls
/**
 * @author David Browaeys
 * @date 28/04/2021
 * @description This batch run for all cases which are linked to COVID19 and were flag as Not Eligible. 
 * It will call the eligibility vaccine rule engine that will return the list of candidate vaccine
 * @example 
 * Database.executeBatch(new EligibilityVaccineMassRecalcBatch('COVID19'),200);
 */
public without sharing class EligibilityVaccineMassRecalcBatch implements Database.Batchable<SObject>{
    public static final String query = 'SELECT ID, AccountId, Status, Eligibility_Status__c, Consent_Status__c FROM Case WHERE RecordType.DeveloperName = \'Vaccine_Application\' AND Disease__c = :diseaseKey AND ContactId NOT IN (SELECT Recipient_Patient__c FROM HealthCloudGA__EhrImmunization__c WHERE Status__c = \'Complete\')';		
    
    String diseaseKey;
    String filterCondition;
    public EligibilityVaccineMassRecalcBatch(String diseaseKey, String filterCondition){
        this.diseaseKey = diseaseKey;
        this.filterCondition = filterCondition;
    }

    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        if(this.filterCondition == null || this.filterCondition == '') { 	
            return Database.getQueryLocator(query);
        } else {
            return Database.getQueryLocator(query + ' AND ' + this.filterCondition);
        }
    }

    public void execute(Database.BatchableContext batchableContext, List<Case> scope)  {
        Map<ID, Case> cases = new Map<ID, Case>(scope);
        EligibilityVaccineRuleEngine handler = new EligibilityVaccineRuleEngine(diseaseKey).start();
        EligibilityVaccineRuleEngine.CandidateVaccineEvent records = handler.execute(cases.keySet());

        // capture all previously eligible cases
        List<Case> previouslyEligibleCases = new List<Case>();
        for(Case c : scope) {
            if(c.Eligibility_Status__c == 'Eligible') {
                previouslyEligibleCases.add(c);
            }
        }
            
        for (Candidate_Vaccine__c cv : records.toInsert) {
            Case thisCase = cases.get(cv.Vaccine_Application__c);

            cv.Account__c = thisCase.AccountId;
            thisCase.Site_Category__c = cv.Eligibility_Vaccine_Group__r.Site_Category__c;
            thisCase.Eligibility_Status__c = 'Eligible';
            thisCase.Eligibility_Vaccine_Group__c = cv.Eligibility_Vaccine_Group__c;
        }
        Database.delete(records.toDelete, false);
        Database.insert(records.toInsert, false);
        Database.update(cases.values(), false);
    }
    
    public void finish(Database.BatchableContext batchableContext){
        System.debug('Finish');
    }
}